table AMZN
	lineageTag: af87c4d1-b83e-4658-b39c-ac276ce7dd2b

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1134886a-768c-423c-945c-7c7b5cdb4c7c
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: ab44f6f2-8e45-47e9-a1bd-045bccb9ea7f
			defaultHierarchy: LocalDateTable_bae0218a-eb3e-4747-ab35-4b60c5fa233a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 292a8a30-6bb9-4109-85db-5568ad38fc80
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: b920fd93-ea9e-4841-b97c-553840b26c9b
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: db46d2f5-346d-4652-87cb-6decf64d642d
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 2ce9c483-97af-46e1-bae4-5338670eb367
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: b39c3a6f-2456-47f6-ab63-b746a900bef2
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: ca462202-d486-4eb1-bba6-b3db08e6a496
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("F:\PBIBroTraining\PBIBroTraining\AMZN.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

